### ISSUE TITLE
V2 compatible

### ISSUE THREAD

**Issue by pitcher-pim** [arnoson/vite-plugin-live-reload#1]
Any update for making V2 compatible? Getting an error which has been changed since V2 I think.
`plugin.configureServer is not a function`

**Comment by arnoson** [comment]
I haven't used V2 but I will look into this!

**Comment by arnoson** [comment]
I created an a beta version (messed up the verison number a bit so we're jumping from 0.1.2 to 2.0 ;) you can install it with `npm i -D vite-plugin-live-reload@beta`. Everything should be working again!

**Comment by arnoson** [comment]
Version `2.0.0` is now released, so the plugin is working with vite 2 by default
