### ISSUE TITLE
Add option to configure watcher interval

### ISSUE THREAD

**Issue by Pombal** [arnoson/vite-plugin-live-reload#12]
Hi,

Right now the pages reload as I type which is not as useful when I'm in the middle of a change.
Ideally the page would reload after a configurable delay (and if new changes are detected, the timeout would reset).

**Comment by arnoson** [comment]
Hi, I'll have to check this out, but it shouldn't reload on type, the watcher should only fire on file save

**Comment by Pombal** [comment]
I since found out I had an extension auto saving, it was supposed to only work for a specific language but it was overreaching. thanks!
