### ISSUE TITLE
Load new photos in productive mode

### ISSUE THREAD

**Issue by jonasesser** [arnoson/vite-plugin-live-reload#8]
Hello,

is it possible with  liveReload to populate new added photos (*.png) to vite webserver?
Currently I add dynamic new photos to a folder  /webviews/photos. But I can only load them with vue3 after I restarted the server. But they should be dynamically added.

Any ideas?

Thanks in advanced

**Comment by arnoson** [comment]
Hi, im not sure if I understand what you mean, can you explain it a bit more? This plugin simply performs a page reload when a watched file has changed. So you can watch png files, but this plugin doesn't restart vite's dev server at all.

**Comment by jonasesser** [comment]
Want add new photos. Like if a photo will be uploaded by a user. But I save it from another process into the public directory. But vite/vue cannot render it. The following code just works after rebuild the server:

```
<img :src="'./photos/' + hash + '.png'" alt="" />
```

Also with absolute path /photos/... its not working. I thought this cannot be complicated. Maybe I missunderstand something simple.

**Comment by jonasesser** [comment]
My builded production folder looks like: https://i.postimg.cc/nrd6H18r/Screenshot-2022-11-19-235125.png

**Comment by arnoson** [comment]
This plugin is only meant for development. Vite isn't even inlcuded in production.
